version: "3.9"

services:
  app:
    image: node:16.14.0-bullseye-slim
    working_dir: /app
    volumes:
      - .:/app:cached
      - next:/app/.next
      - node_modules:/app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    command: sh -c "yarn && yarn dev"
    ports:
      - ${APP_PORT:-3000}:3000

volumes:
  next:
  node_modules:
  yarn-cache:
